In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import time
import pickle

In [2]:
# Setting pandas to display columns
pd.set_option('display.max_columns', None)

In [3]:
nfl_small = pd.read_csv('nfl_small.csv')
nfl_small.shape

(87277, 51)

In [4]:
# Dropping unused index column and sorting to allow for future calculations
nfl_small = nfl_small.drop(columns=['Unnamed: 0']).sort_values(by=['game_id','play_id'])

In [5]:
nfl_small.head(5)

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass
0,362094,44,2017090700,2017-09-07,15:00,900.0,1800.0,3600.0,Half1,0,1,NE,KC,NE,home,KC,KC,35.0,1,0,NaN,0.0,KC 35,0,73,C.Santos kicks 64 yards from KC 35 to NE 1. D....,kickoff,0.0,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,0,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,362095,68,2017090700,2017-09-07,14:55,895.0,1795.0,3595.0,Half1,0,1,NE,KC,NE,home,KC,NE,73.0,1,0,1.0,0.0,NE 27,10,0,(14:55) NE 12-Brady 18th season as Patriots QB...,pass,0.0,deep,27.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,362096,94,2017090700,2017-09-07,14:49,889.0,1789.0,3589.0,Half1,0,1,NE,KC,NE,home,KC,NE,73.0,1,0,2.0,0.0,NE 27,10,8,(14:49) T.Brady pass short right to R.Burkhead...,pass,8.0,short,1.0,7.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,362097,118,2017090700,2017-09-07,14:14,854.0,1754.0,3554.0,Half1,0,1,NE,KC,NE,home,KC,NE,65.0,1,0,3.0,0.0,NE 35,2,73,(14:14) (Shotgun) J.White left guard to NE 43 ...,run,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,362098,139,2017090700,2017-09-07,13:52,832.0,1732.0,3532.0,Half1,0,1,NE,KC,NE,home,KC,NE,57.0,1,0,1.0,0.0,NE 43,10,19,"(13:52) (No Huddle, Shotgun) J.White up the mi...",run,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

<h2>Data Cleaning</h2>

In [6]:
# Changing date object to date format
nfl_small['game_date'] = pd.to_datetime(nfl_small['game_date'])
nfl_small.head(2)

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass
0,362094,44,2017090700,2017-09-07,15:00,900.0,1800.0,3600.0,Half1,0,1,NE,KC,NE,home,KC,KC,35.0,1,0,NaN,0.0,KC 35,0,73,C.Santos kicks 64 yards from KC 35 to NE 1. D....,kickoff,0.0,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,0,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,362095,68,2017090700,2017-09-07,14:55,895.0,1795.0,3595.0,Half1,0,1,NE,KC,NE,home,KC,NE,73.0,1,0,1.0,0.0,NE 27,10,0,(14:55) NE 12-Brady 18th season as Patriots QB...,pass,0.0,deep,27.0,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# Inspecting datatypes
nfl_small.dtypes

index                                 int64
play_id                               int64
game_id                               int64
game_date                    datetime64[ns]
time                                 object
quarter_seconds_remaining           float64
half_seconds_remaining              float64
game_seconds_remaining              float64
game_half                            object
quarter_end                           int64
qtr                                   int64
home_team                            object
away_team                            object
posteam                              object
posteam_type                         object
defteam                              object
side_of_field                        object
yardline_100                        float64
drive                                 int64
sp                                    int64
down                                float64
goal_to_go                          float64
yrdln                                object
ydstogo                               int64
ydsnet                                int64
desc                                 object
play_type                            object
yards_gained                        float64
pass_length                          object
air_yards                           float64
yards_after_catch                   float64
field_goal_result                    object
kick_distance                       float64
extra_point_result                   object
two_point_conv_result                object
td_team                              object
total_home_score                      int64
total_away_score                      int64
posteam_score                       float64
defteam_score                       float64
sack                                float64
touchdown                           float64
pass_touchdown                      float64
rush_touchdown                      float64
return_touchdown                    float64
extra_point_attempt                 float64
two_point_attempt                   float64
field_goal_attempt                  float64
fumble                              float64
complete_pass                       float64
dtype: object

In [8]:
# Creating a function that examines missing values in a dataframe easily. This can re-used later.
def null_count_func(dataframe):
    columns = list(dataframe.columns)

    for column in columns:
        total = dataframe[column].count()
        null_cnt = dataframe[column].isnull().sum()
        print('Column {} has {} real values, and {} null values'.format(column,total,null_cnt))

In [9]:
null_count_func(nfl_small)

Column index has 87277 real values, and 0 null values
Column play_id has 87277 real values, and 0 null values
Column game_id has 87277 real values, and 0 null values
Column game_date has 87277 real values, and 0 null values
Column time has 87240 real values, and 37 null values
Column quarter_seconds_remaining has 87240 real values, and 37 null values
Column half_seconds_remaining has 87216 real values, and 61 null values
Column game_seconds_remaining has 87218 real values, and 59 null values
Column game_half has 87277 real values, and 0 null values
Column quarter_end has 87277 real values, and 0 null values
Column qtr has 87277 real values, and 0 null values
Column home_team has 87277 real values, and 0 null values
Column away_team has 87277 real values, and 0 null values
Column posteam has 84286 real values, and 2991 null values
Column posteam_type has 84375 real values, and 2902 null values
Column defteam has 84375 real values, and 2902 null values
Column side_of_field has 87132 real values, and 145 null values
Column yardline_100 has 84321 real values, and 2956 null values
Column drive has 87277 real values, and 0 null values
Column sp has 87277 real values, and 0 null values
Column down has 73480 real values, and 13797 null values
Column goal_to_go has 84410 real values, and 2867 null values
Column yrdln has 87132 real values, and 145 null values
Column ydstogo has 87277 real values, and 0 null values
Column ydsnet has 87277 real values, and 0 null values
Column desc has 87277 real values, and 0 null values
Column play_type has 84375 real values, and 2902 null values
Column yards_gained has 87277 real values, and 0 null values
Column pass_length has 33800 real values, and 53477 null values
Column air_yards has 33928 real values, and 53349 null values
Column yards_after_catch has 21566 real values, and 65711 null values
Column field_goal_result has 1917 real values, and 85360 null values
Column kick_distance has 9524 real values, and 77753 null values
Column extra_point_result has 2147 real values, and 85130 null values
Column two_point_conv_result has 192 real values, and 87085 null values
Column td_team has 2507 real values, and 84770 null values
Column total_home_score has 87277 real values, and 0 null values
Column total_away_score has 87277 real values, and 0 null values
Column posteam_score has 83881 real values, and 3396 null values
Column defteam_score has 83881 real values, and 3396 null values
Column sack has 84375 real values, and 2902 null values
Column touchdown has 84375 real values, and 2902 null values
Column pass_touchdown has 84375 real values, and 2902 null values
Column rush_touchdown has 84375 real values, and 2902 null values
Column return_touchdown has 84375 real values, and 2902 null values
Column extra_point_attempt has 84375 real values, and 2902 null values
Column two_point_attempt has 84375 real values, and 2902 null values
Column field_goal_attempt has 84375 real values, and 2902 null values
Column fumble has 84375 real values, and 2902 null values
Column complete_pass has 84375 real values, and 2902 null values

From the null check function, we see quite a few columns with nulls, but I am unsure if that is on purpose or just data gaps.

I plan to explore:   
1. time - Done - fill forward
2. quarter_seconds_remaining - Done - fill forward
3. half_seconds_remaining - Done - fill forward
4. game_seconds_remaining - Done - fill forward
5. posteam - Done - fill forward
6. posteam_type - Done - fill forward
7. defteam - Done - fill forward
8. yardline_100 - Done - dropping nulls
9. down - Done - dropping nulls
10. goal_to_go - Done - dropping nulls
11. play_type - Done - dropping nulls
12. pass_length (ensure it's de-duped from runs) - Done - Fill with zero. Most nulls are kicks or runs. Sacks are also null
13. air_yards (ensure it's de-duped from runs) - Done - Same as pass_length. Ensure we can use this for incomplete passes?
14. yards_after_catch (ensure it's de-duped from runs) - Done - Mostly the same as above, but also includes nulls for incomplete passes
15. posteam_score - Done - beginning of game, so fill with zero
16. defteam_score - Done - beginning of game, so fill with zero

In [10]:
nfl_small.shape

(87277, 50)

In [11]:
# Removing BLANK PLAY
blank_play_drop = list(nfl_small[nfl_small['desc']=='BLANK PLAY'].index)
nfl_small.drop(nfl_small.index[blank_play_drop], inplace=True)
nfl_small.shape

(87272, 50)

In [12]:
# Forward fill time for weather delays ***Potential Improvement - Incorprate Delay Times***
nfl_small['time'] = nfl_small['time'].fillna(method='pad')
nfl_small['quarter_seconds_remaining'] = nfl_small['quarter_seconds_remaining'].fillna(method='pad')
nfl_small['half_seconds_remaining'] = nfl_small['half_seconds_remaining'].fillna(method='pad')
nfl_small['game_seconds_remaining'] = nfl_small['game_seconds_remaining'].fillna(method='pad')

In [13]:
# Forward filling the possession columns
nfl_small['posteam'] = nfl_small['posteam'].fillna(method='pad')
nfl_small['posteam_type'] = nfl_small['posteam_type'].fillna(method='pad')
nfl_small['defteam'] = nfl_small['defteam'].fillna(method='pad')

In [14]:
# Other fill operations
nfl_small['yardline_100'] = nfl_small['yardline_100'].fillna(method='pad')
nfl_small['pass_length'] = nfl_small['pass_length'].fillna(0)
nfl_small['air_yards'] = nfl_small['air_yards'].fillna(0)
nfl_small['yards_after_catch'] = nfl_small['yards_after_catch'].fillna(0)
nfl_small['posteam_score'] = nfl_small['posteam_score'].fillna(0)
nfl_small['defteam_score'] = nfl_small['posteam_score'].fillna(0)

In [15]:
# Columns for dropping null records  ***Cannot drop these rows yet. It breaks our time cleaning below***
# nfl_small = nfl_small[nfl_small['down'].notna()]
# nfl_small.shape

In [16]:
# Columns for dropping null records  ***Cannot drop these rows yet. It breaks our time cleaning below***
# nfl_small = nfl_small[nfl_small['goal_to_go'].notna()]
# nfl_small.shape

In [17]:
# Columns for dropping null records  ***Cannot drop these rows yet. It breaks our time cleaning below***
# nfl_small = nfl_small[nfl_small['play_type'].notna()]
# nfl_small.shape

In [18]:
null_count_func(nfl_small)

Column index has 87272 real values, and 0 null values
Column play_id has 87272 real values, and 0 null values
Column game_id has 87272 real values, and 0 null values
Column game_date has 87272 real values, and 0 null values
Column time has 87272 real values, and 0 null values
Column quarter_seconds_remaining has 87272 real values, and 0 null values
Column half_seconds_remaining has 87272 real values, and 0 null values
Column game_seconds_remaining has 87272 real values, and 0 null values
Column game_half has 87272 real values, and 0 null values
Column quarter_end has 87272 real values, and 0 null values
Column qtr has 87272 real values, and 0 null values
Column home_team has 87272 real values, and 0 null values
Column away_team has 87272 real values, and 0 null values
Column posteam has 87272 real values, and 0 null values
Column posteam_type has 87272 real values, and 0 null values
Column defteam has 87272 real values, and 0 null values
Column side_of_field has 87127 real values, and 145 null values
Column yardline_100 has 87272 real values, and 0 null values
Column drive has 87272 real values, and 0 null values
Column sp has 87272 real values, and 0 null values
Column down has 73478 real values, and 13794 null values
Column goal_to_go has 84408 real values, and 2864 null values
Column yrdln has 87127 real values, and 145 null values
Column ydstogo has 87272 real values, and 0 null values
Column ydsnet has 87272 real values, and 0 null values
Column desc has 87272 real values, and 0 null values
Column play_type has 84373 real values, and 2899 null values
Column yards_gained has 87272 real values, and 0 null values
Column pass_length has 87272 real values, and 0 null values
Column air_yards has 87272 real values, and 0 null values
Column yards_after_catch has 87272 real values, and 0 null values
Column field_goal_result has 1917 real values, and 85355 null values
Column kick_distance has 9524 real values, and 77748 null values
Column extra_point_result has 2147 real values, and 85125 null values
Column two_point_conv_result has 192 real values, and 87080 null values
Column td_team has 2507 real values, and 84765 null values
Column total_home_score has 87272 real values, and 0 null values
Column total_away_score has 87272 real values, and 0 null values
Column posteam_score has 87272 real values, and 0 null values
Column defteam_score has 87272 real values, and 0 null values
Column sack has 84373 real values, and 2899 null values
Column touchdown has 84373 real values, and 2899 null values
Column pass_touchdown has 84373 real values, and 2899 null values
Column rush_touchdown has 84373 real values, and 2899 null values
Column return_touchdown has 84373 real values, and 2899 null values
Column extra_point_attempt has 84373 real values, and 2899 null values
Column two_point_attempt has 84373 real values, and 2899 null values
Column field_goal_attempt has 84373 real values, and 2899 null values
Column fumble has 84373 real values, and 2899 null values
Column complete_pass has 84373 real values, and 2899 null values

<h2>Field Exploration is Below. Summarizing and applying changes above</h2>

In [19]:
# Null time also affects other time columns so will fill all
nfl_small[nfl_small['time'].isnull()].head()

Empty DataFrame
Columns: [index, play_id, game_id, game_date, time, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, qtr, home_team, away_team, posteam, posteam_type, defteam, side_of_field, yardline_100, drive, sp, down, goal_to_go, yrdln, ydstogo, ydsnet, desc, play_type, yards_gained, pass_length, air_yards, yards_after_catch, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, td_team, total_home_score, total_away_score, posteam_score, defteam_score, sack, touchdown, pass_touchdown, rush_touchdown, return_touchdown, extra_point_attempt, two_point_attempt, field_goal_attempt, fumble, complete_pass]
Index: []

In [20]:
# Most look like stoppage in play. I will try to backfill from previous time
# nfl_small[nfl_small['time'].isnull()].groupby('desc')['desc'].count()

In [21]:
# Exploring blank plays, it looks like we can remove the rows from the dataset
nfl_small[(nfl_small['game_id']==2017091000) & (nfl_small['play_id'].between(1062,1102))]

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass
242,362336,1062,2017091000,2017-09-10,13:59,839.0,839.0,2639.0,Half1,0,2,BUF,NYJ,BUF,home,NYJ,NYJ,34.0,5,0,2.0,0.0,NYJ 34,10,77,(13:59) (Shotgun) T.Taylor pass short middle t...,pass,12.0,short,4.0,8.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
244,362338,1102,2017091000,2017-09-10,13:22,802.0,802.0,2602.0,Half1,0,2,BUF,NYJ,BUF,home,NYJ,NYJ,22.0,5,0,1.0,0.0,NYJ 22,10,71,(13:22) M.Tolbert right tackle to NYJ 8 for 14...,run,14.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
blank_play_drop = list(nfl_small[nfl_small['desc']=='BLANK PLAY'].index)
blank_play_drop

[11487, 12684]

In [23]:
nfl_small.drop(nfl_small.index[blank_play_drop], inplace=True)

In [24]:
list(nfl_small[nfl_small['desc']=='BLANK PLAY'].index)

[11487, 12684]

In [25]:
# Exploring delays, it looks like we will need to account for delay times, but can drop rows after
# nfl_small[(nfl_small['game_id']==2017091710) & (nfl_small['play_id'].between(750,850))]

In [26]:
# Exploring end of half/game, it looks like we should also account for time, but can drop rows after
# nfl_small[(nfl_small['game_id']==2017092401) & (nfl_small['play_id'].between(2500,2600))]

In [27]:
# Forward fill time for weather delays ***Potential Improvement - Incorprate Delay Times***
nfl_small['time'] = nfl_small['time'].fillna(method='pad')
nfl_small['quarter_seconds_remaining'] = nfl_small['quarter_seconds_remaining'].fillna(method='pad')
nfl_small['half_seconds_remaining'] = nfl_small['half_seconds_remaining'].fillna(method='pad')
nfl_small['game_seconds_remaining'] = nfl_small['game_seconds_remaining'].fillna(method='pad')

<h2>Exploring posteam nulls</h2>
5. posteam
6. posteam_type
7. defteam

In [28]:
# All null posteam is due to stoppage in play. Will forward fill team from previous record
# nfl_small[nfl_small['posteam'].isnull()].groupby('desc')['desc'].count()

In [29]:
# Same as posteam
# nfl_small[nfl_small['posteam_type'].isnull()].groupby('desc')['desc'].count()

In [30]:
# Same as both above
# nfl_small[nfl_small['defteam'].isnull()].groupby('desc')['desc'].count()

In [31]:
# Forward filling the possession columns
nfl_small['posteam'] = nfl_small['posteam'].fillna(method='pad')
nfl_small['posteam_type'] = nfl_small['posteam_type'].fillna(method='pad')
nfl_small['defteam'] = nfl_small['defteam'].fillna(method='pad')

<h2>Exploring yardline_100 nulls</h2>

In [32]:
# Null yardline_100 appears to match time nulls and are stoppages in play
# nfl_small[nfl_small['yardline_100'].isnull()].head()

In [33]:
# nfl_small[nfl_small['yardline_100'].isnull()]['desc'].unique()

In [34]:
nfl_small['yardline_100'] = nfl_small['yardline_100'].fillna(method='pad')

<h2>Exploring goal_to_go nulls</h2>

In [35]:
# Same as yardline
nfl_small[nfl_small['goal_to_go'].isnull()].head()

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass
9,362103,279,2017090700,2017-09-07,12:21,741.0,1641.0,3441.0,Half1,0,1,NE,KC,NE,home,KC,KC,14.0,1,0,1.0,NaN,KC 2,2,71,(12:21) N.Solder reported in as eligible. M.G...,NaN,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,362139,1202,2017090700,2017-09-07,00:00,0.0,900.0,2700.0,Half1,1,1,NE,KC,NE,home,KC,KC,8.0,5,0,NaN,NaN,KC 8,0,67,END QUARTER 1,NaN,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,7,7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,362174,2017,2017090700,2017-09-07,02:00,120.0,120.0,1920.0,Half1,0,2,NE,KC,KC,away,NE,KC,89.0,10,0,NaN,NaN,KC 11,0,12,Two-Minute Warning,NaN,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,17,7,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,362191,2398,2017090700,2017-09-07,00:00,0.0,0.0,1800.0,Half1,1,2,NE,KC,NE,home,KC,NE,82.0,11,0,NaN,NaN,NE 18,0,-1,END QUARTER 2,NaN,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,17,14,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,362194,2451,2017090700,2017-09-07,14:21,861.0,1761.0,1761.0,Half2,0,3,NE,KC,KC,away,NE,KC,75.0,12,0,1.0,NaN,KC 35,10,10,(14:21),NaN,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,17,14,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
nfl_small[nfl_small['goal_to_go'].isnull()]['play_id'].count()

2864

In [37]:
# All play types are NAN
nfl_small[nfl_small['goal_to_go'].isnull()].groupby('play_type')['play_type'].count()

Series([], Name: play_type, dtype: int64)

In [38]:
# goal_to_go is an indicator
nfl_small.groupby('goal_to_go')['goal_to_go'].count()

goal_to_go
0.0    80170
1.0     4236
Name: goal_to_go, dtype: int64

In [40]:
null_goal_to_go_drop = list(nfl_small[nfl_small['goal_to_go'].isnull()].index)
len(null_goal_to_go_drop)

2864

In [43]:
# nfl_small.drop(nfl_small.index[null_goal_to_go_drop], inplace=True)

<h2>Exploring play_type nulls</h2>

In [44]:
# All are stoppages of play. Will exclude
# nfl_small[nfl_small['play_type'].isnull()].head()
# All play types are NAN
# nfl_small[nfl_small['play_type'].isnull()].groupby('desc')['desc'].count()
nfl_small.shape

(87270, 50)

In [45]:
nfl_small = nfl_small[nfl_small['play_type'].notna()]
nfl_small.shape

(84371, 50)

<h2>Exploring pass_length nulls</h2>

In [46]:
# Majority are kicks, stoppages of play (will be excluded) or runs
# nfl_small[nfl_small['pass_length'].isnull()].head()
nfl_small[nfl_small['pass_length'].isnull()].groupby('play_type')['play_type'].count()

Series([], Name: play_type, dtype: int64)

In [48]:
# Exploring null pass_length for pass plays, which appear to be sacks
nfl_small[(nfl_small['pass_length'].isnull()) & (nfl_small['play_type'] == 'pass')].head()

Empty DataFrame
Columns: [index, play_id, game_id, game_date, time, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, qtr, home_team, away_team, posteam, posteam_type, defteam, side_of_field, yardline_100, drive, sp, down, goal_to_go, yrdln, ydstogo, ydsnet, desc, play_type, yards_gained, pass_length, air_yards, yards_after_catch, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, td_team, total_home_score, total_away_score, posteam_score, defteam_score, sack, touchdown, pass_touchdown, rush_touchdown, return_touchdown, extra_point_attempt, two_point_attempt, field_goal_attempt, fumble, complete_pass]
Index: []

In [49]:
# All null pass_length plays for play type = pass are sacks. 
# Will fill all nulls with zero and need to use play_type to evaluate.
regex = 'sacked'
series = nfl_small[(nfl_small['pass_length'].isnull()) & (nfl_small['play_type'] == 'pass')]['desc']
series.count(), series.str.contains(regex).count()

(0, 0)

In [50]:
nfl_small['pass_length'] = nfl_small['pass_length'].fillna(0)

<h2>Exploring air_yards nulls</h2>

In [51]:
# Same distribution so will fill with zero
nfl_small[nfl_small['air_yards'].isnull()].groupby('play_type')['play_type'].count()

Series([], Name: play_type, dtype: int64)

In [52]:
nfl_small['air_yards'] = nfl_small['air_yards'].fillna(0)

<h2>Exploring yards_after_catch nulls</h2>

In [53]:
# A lot more nulls for pass plays, so will investigate non-sacks
nfl_small[nfl_small['yards_after_catch'].isnull()].groupby('play_type')['play_type'].count()

Series([], Name: play_type, dtype: int64)

In [54]:
regex = 'sacked'
series = nfl_small[(nfl_small['yards_after_catch'].isnull()) & (nfl_small['play_type'] == 'pass')]['desc']
series.count(), series.str.contains(regex).count()

(0, 0)

In [55]:
# Look like incomplete passes
nfl_small[(nfl_small['yards_after_catch'].isnull()) & (nfl_small['play_type'] == 'pass')\
         & (~nfl_small['desc'].str.contains(regex))
         ].head()

Empty DataFrame
Columns: [index, play_id, game_id, game_date, time, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, qtr, home_team, away_team, posteam, posteam_type, defteam, side_of_field, yardline_100, drive, sp, down, goal_to_go, yrdln, ydstogo, ydsnet, desc, play_type, yards_gained, pass_length, air_yards, yards_after_catch, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, td_team, total_home_score, total_away_score, posteam_score, defteam_score, sack, touchdown, pass_touchdown, rush_touchdown, return_touchdown, extra_point_attempt, two_point_attempt, field_goal_attempt, fumble, complete_pass]
Index: []

In [56]:
nfl_small[(nfl_small['yards_after_catch'].isnull()) & (nfl_small['play_type'] == 'pass')\
         & (~nfl_small['desc'].str.contains(regex)) & (nfl_small['desc'].str.contains('incomplete'))]['play_id'].count()

0

In [57]:
nfl_small['yards_after_catch'] = nfl_small['yards_after_catch'].fillna(0)

<h2>Exploring posteam_score nulls</h2>

In [58]:
nfl_small.head(5)

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass
0,362094,44,2017090700,2017-09-07,15:00,900.0,1800.0,3600.0,Half1,0,1,NE,KC,NE,home,KC,KC,35.0,1,0,NaN,0.0,KC 35,0,73,C.Santos kicks 64 yards from KC 35 to NE 1. D....,kickoff,0.0,0,0.0,0.0,NaN,64.0,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,362095,68,2017090700,2017-09-07,14:55,895.0,1795.0,3595.0,Half1,0,1,NE,KC,NE,home,KC,NE,73.0,1,0,1.0,0.0,NE 27,10,0,(14:55) NE 12-Brady 18th season as Patriots QB...,pass,0.0,deep,27.0,0.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,362096,94,2017090700,2017-09-07,14:49,889.0,1789.0,3589.0,Half1,0,1,NE,KC,NE,home,KC,NE,73.0,1,0,2.0,0.0,NE 27,10,8,(14:49) T.Brady pass short right to R.Burkhead...,pass,8.0,short,1.0,7.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,362097,118,2017090700,2017-09-07,14:14,854.0,1754.0,3554.0,Half1,0,1,NE,KC,NE,home,KC,NE,65.0,1,0,3.0,0.0,NE 35,2,73,(14:14) (Shotgun) J.White left guard to NE 43 ...,run,8.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,362098,139,2017090700,2017-09-07,13:52,832.0,1732.0,3532.0,Half1,0,1,NE,KC,NE,home,KC,NE,57.0,1,0,1.0,0.0,NE 43,10,19,"(13:52) (No Huddle, Shotgun) J.White up the mi...",run,3.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
# All are beginning of game, so will fill with zero
nfl_small[nfl_small['posteam_score'].isnull()].groupby(['play_type','qtr','game_seconds_remaining'])['play_type'].count()

Series([], Name: play_type, dtype: int64)

In [60]:
nfl_small['posteam_score'] = nfl_small['posteam_score'].fillna(0)

<h2>Exploring defteam_score nulls</h2>

In [61]:
# All are beginning of game, so will fill with zero
nfl_small[nfl_small['defteam_score'].isnull()].groupby(['play_type','qtr','game_seconds_remaining'])['play_type'].count()

Series([], Name: play_type, dtype: int64)

In [62]:
nfl_small['defteam_score'] = nfl_small['defteam_score'].fillna(0)

In [63]:
null_count_func(nfl_small)

Column index has 84371 real values, and 0 null values
Column play_id has 84371 real values, and 0 null values
Column game_id has 84371 real values, and 0 null values
Column game_date has 84371 real values, and 0 null values
Column time has 84371 real values, and 0 null values
Column quarter_seconds_remaining has 84371 real values, and 0 null values
Column half_seconds_remaining has 84371 real values, and 0 null values
Column game_seconds_remaining has 84371 real values, and 0 null values
Column game_half has 84371 real values, and 0 null values
Column quarter_end has 84371 real values, and 0 null values
Column qtr has 84371 real values, and 0 null values
Column home_team has 84371 real values, and 0 null values
Column away_team has 84371 real values, and 0 null values
Column posteam has 84371 real values, and 0 null values
Column posteam_type has 84371 real values, and 0 null values
Column defteam has 84371 real values, and 0 null values
Column side_of_field has 84282 real values, and 89 null values
Column yardline_100 has 84371 real values, and 0 null values
Column drive has 84371 real values, and 0 null values
Column sp has 84371 real values, and 0 null values
Column down has 73365 real values, and 11006 null values
Column goal_to_go has 84371 real values, and 0 null values
Column yrdln has 84282 real values, and 89 null values
Column ydstogo has 84371 real values, and 0 null values
Column ydsnet has 84371 real values, and 0 null values
Column desc has 84371 real values, and 0 null values
Column play_type has 84371 real values, and 0 null values
Column yards_gained has 84371 real values, and 0 null values
Column pass_length has 84371 real values, and 0 null values
Column air_yards has 84371 real values, and 0 null values
Column yards_after_catch has 84371 real values, and 0 null values
Column field_goal_result has 1917 real values, and 82454 null values
Column kick_distance has 9524 real values, and 74847 null values
Column extra_point_result has 2147 real values, and 82224 null values
Column two_point_conv_result has 192 real values, and 84179 null values
Column td_team has 2507 real values, and 81864 null values
Column total_home_score has 84371 real values, and 0 null values
Column total_away_score has 84371 real values, and 0 null values
Column posteam_score has 84371 real values, and 0 null values
Column defteam_score has 84371 real values, and 0 null values
Column sack has 84371 real values, and 0 null values
Column touchdown has 84371 real values, and 0 null values
Column pass_touchdown has 84371 real values, and 0 null values
Column rush_touchdown has 84371 real values, and 0 null values
Column return_touchdown has 84371 real values, and 0 null values
Column extra_point_attempt has 84371 real values, and 0 null values
Column two_point_attempt has 84371 real values, and 0 null values
Column field_goal_attempt has 84371 real values, and 0 null values
Column fumble has 84371 real values, and 0 null values
Column complete_pass has 84371 real values, and 0 null values

<h2>Exploring down nulls - Removing null downs since vast majoirty are Kickoffs and PAT plays</h2>

In [64]:
#Mostly kickoffs and timeouts which will be out of scope for our analysis. Removing
# nfl_small[nfl_small['down'].isnull()].groupby('desc')['desc'].count()
null_down_drop = list(nfl_small[nfl_small['down'].isnull()].index)
len(null_down_drop)

11006

In [65]:
nfl_small[nfl_small['down'].isnull()].groupby('play_type')['play_type'].count()

play_type
extra_point    2098
kickoff        4941
no_play        3752
pass            139
qb_kneel         28
run              48
Name: play_type, dtype: int64

In [66]:
nfl_small.drop(nfl_small.index[null_down_drop], inplace=True)

IndexError: index 84373 is out of bounds for axis 0 with size 84371

<h2> Adding Time: We must add a column that is directly or approximates time of day, so we are able to join with our weather data</h2>

In [67]:
# Need team names to create time DF
# list(nfl_small['home_team'].unique())

In [68]:
def game_schedule(year):
    
    import requests
    import urllib.request
    import time
    import pandas as pd
    
    url = 'https://www.pro-football-reference.com/years/' + year + '/games.htm'
    
    df = pd.read_html(url)[0]
    
    # Renaming column that determine location of game
    df = df.rename(columns={"Unnamed: 5": "location"})
    
    df['year'] = year
    
    df['home_team'] = df.apply(lambda x : x['Loser/tie'] if x['location'] == '@' else x['Winner/tie'],axis=1)
    df['away_team'] = df.apply(lambda x : x['Winner/tie'] if x['location'] == '@' else x['Loser/tie'],axis=1)
    
    team_mapping = {
    'Arizona Cardinals':'ARI',
    'Atlanta Falcons':'ATL',
    'Baltimore Ravens':'BAL',
    'Buffalo Bills':'BUF',
    'Carolina Panthers':'CAR',
    'Chicago Bears':'CHI',
    'Cincinnati Bengals':'CIN',
    'Cleveland Browns':'CLE',
    'Dallas Cowboys':'DAL',
    'Denver Broncos':'DEN',
    'Detroit Lions':'DET',
    'Green Bay Packers':'GB',
    'Houston Texans':'HOU',
    'Indianapolis Colts':'IND',
    'Jacksonville Jaguars':'JAX',
    'Kansas City Chiefs':'KC',
    'Los Angeles Rams':'LA',
    'Los Angeles Chargers':'LAC',
    'Miami Dolphins':'MIA',
    'Minnesota Vikings':'MIN',
    'New England Patriots':'NE',
    'New Orleans Saints':'NO',
    'New York Giants':'NYG',
    'New York Jets':'NYJ',
    'Oakland Raiders':'OAK',
    'Philadelphia Eagles':'PHI',
    'Pittsburgh Steelers':'PIT',
    'Seattle Seahawks':'SEA',
    'San Francisco 49ers':'SF',
    'Tampa Bay Buccaneers':'TB',
    'Tennessee Titans':'TEN',
    'Washington Redskins':'WAS'
    }
    
    # Replacing team names to be consistent with play-by-play data
    df = df.replace({'home_team':team_mapping}).replace({'away_team':team_mapping})
    
    # Removing date headers
    df = df[~df['Date'].isin(['Date','Playoffs'])]
    
    # Casting date object as date
    df['Date'] = pd.to_datetime(df['Date'] + ', ' + year)
    
#     df['Date_time'] = df['Date'] + ', 2017 ' + df['Time']
#     df['Datetime'] = pd.to_datetime(df['Date_time'])
    
    # Casting Time object as time
    df['Start_Time'] = pd.to_datetime(df['Time']).dt.time
    
    return df[['Date','Start_Time','home_team','away_team']]

In [69]:
schd_17 = game_schedule('2017')
schd_17.head(4)

        Date Start_Time home_team away_team
0 2017-09-07   20:30:00        NE        KC
1 2017-09-10   13:00:00       TEN       OAK
2 2017-09-10   13:00:00       CHI       ATL
3 2017-09-10   13:00:00       BUF       NYJ

In [70]:
schd_17.dtypes

Date          datetime64[ns]
Start_Time            object
home_team             object
away_team             object
dtype: object

In [81]:
# Adding join values to add time to kickoff
schd_17['qtr'] = 1
schd_17['play_type'] = 'kickoff'
schd_17['time'] = '15:00'
schd_17.head(5)

        Date Start_Time home_team away_team  qtr play_type   time
0 2017-09-07   20:30:00        NE        KC    1   kickoff  15:00
1 2017-09-10   13:00:00       TEN       OAK    1   kickoff  15:00
2 2017-09-10   13:00:00       CHI       ATL    1   kickoff  15:00
3 2017-09-10   13:00:00       BUF       NYJ    1   kickoff  15:00
4 2017-09-10   13:00:00       CLE       PIT    1   kickoff  15:00

In [84]:
schd_17.dtypes

Date          datetime64[ns]
Start_Time            object
home_team             object
away_team             object
qtr                    int64
play_type             object
time                  object
dtype: object

In [85]:
# Merging schedule data to get start of game
nfl_small2 = nfl_small.merge(schd_17, how = 'left', left_on = ['game_date','home_team','away_team','qtr','play_type','time'],\
                                        right_on = ['Date','home_team','away_team','qtr','play_type','time'])

In [86]:
nfl_small2.drop(columns=['Date'],axis=1,inplace=True)

In [87]:
nfl_small2.dtypes

index                                 int64
play_id                               int64
game_id                               int64
game_date                    datetime64[ns]
time                                 object
quarter_seconds_remaining           float64
half_seconds_remaining              float64
game_seconds_remaining              float64
game_half                            object
quarter_end                           int64
qtr                                   int64
home_team                            object
away_team                            object
posteam                              object
posteam_type                         object
defteam                              object
side_of_field                        object
yardline_100                        float64
drive                                 int64
sp                                    int64
down                                float64
goal_to_go                          float64
yrdln                                object
ydstogo                               int64
ydsnet                                int64
desc                                 object
play_type                            object
yards_gained                        float64
pass_length                          object
air_yards                           float64
yards_after_catch                   float64
field_goal_result                    object
kick_distance                       float64
extra_point_result                   object
two_point_conv_result                object
td_team                              object
total_home_score                      int64
total_away_score                      int64
posteam_score                       float64
defteam_score                       float64
sack                                float64
touchdown                           float64
pass_touchdown                      float64
rush_touchdown                      float64
return_touchdown                    float64
extra_point_attempt                 float64
two_point_attempt                   float64
field_goal_attempt                  float64
fumble                              float64
complete_pass                       float64
Start_Time                           object
dtype: object

In [88]:
# If records are dropped above, time fill will not work
nfl_small2['Start_Time']

0        20:30:00
1             NaN
2             NaN
3             NaN
4             NaN
           ...
84366         NaN
84367         NaN
84368         NaN
84369         NaN
84370         NaN
Name: Start_Time, Length: 84371, dtype: object

In [89]:
# Filling start time for all game rows to add cummulative seconds
nfl_small2['Start_Time'] = nfl_small2['Start_Time'].fillna(method='pad')
nfl_small2['Start_Time'] = nfl_small2.apply(lambda x :\
                                        datetime.combine(x['game_date'],x['Start_Time']),axis=1)

In [90]:
# Adding time difference from each play. Assuming a 3X increase in actual time
nfl_small2['diff'] = nfl_small2.groupby(['game_id'])['game_seconds_remaining'].diff().fillna(0)
nfl_small2['diff'] = nfl_small2['diff']*-3

In [91]:
# Updating start of overtime to have diff equal to zero to account for unexpected time remaining
nfl_small2.loc[(nfl_small2['diff'] < 0)\
               & (nfl_small2['qtr'] == 5)\
               & (nfl_small2['game_seconds_remaining'] == 600),'diff'] = 0

In [92]:
nfl_small2[(nfl_small2['diff'] < 0) & (nfl_small2['qtr'] == 5) & (nfl_small2['game_seconds_remaining'] == 600)]

Empty DataFrame
Columns: [index, play_id, game_id, game_date, time, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, qtr, home_team, away_team, posteam, posteam_type, defteam, side_of_field, yardline_100, drive, sp, down, goal_to_go, yrdln, ydstogo, ydsnet, desc, play_type, yards_gained, pass_length, air_yards, yards_after_catch, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, td_team, total_home_score, total_away_score, posteam_score, defteam_score, sack, touchdown, pass_touchdown, rush_touchdown, return_touchdown, extra_point_attempt, two_point_attempt, field_goal_attempt, fumble, complete_pass, Start_Time, diff]
Index: []

In [93]:
# Summing up all time diff
nfl_small2['diff'] = nfl_small2.groupby(['game_id'])['diff'].cumsum()

In [94]:
# Sorting data by game_id and play_id removes negative diff, but we still need to see how overtime looks
nfl_small2[nfl_small2['diff'] < 0].head()

Empty DataFrame
Columns: [index, play_id, game_id, game_date, time, quarter_seconds_remaining, half_seconds_remaining, game_seconds_remaining, game_half, quarter_end, qtr, home_team, away_team, posteam, posteam_type, defteam, side_of_field, yardline_100, drive, sp, down, goal_to_go, yrdln, ydstogo, ydsnet, desc, play_type, yards_gained, pass_length, air_yards, yards_after_catch, field_goal_result, kick_distance, extra_point_result, two_point_conv_result, td_team, total_home_score, total_away_score, posteam_score, defteam_score, sack, touchdown, pass_touchdown, rush_touchdown, return_touchdown, extra_point_attempt, two_point_attempt, field_goal_attempt, fumble, complete_pass, Start_Time, diff]
Index: []

In [95]:
# Convert time diff to timedelta to allow for adding to current time
from datetime import timedelta
nfl_small2['diff'] = nfl_small2.apply(lambda x : timedelta(seconds=x['diff']),axis=1)

In [96]:
nfl_small2[['Start_Time','diff']].dtypes

Start_Time     datetime64[ns]
diff          timedelta64[ns]
dtype: object

In [97]:
nfl_small2['Estimated_Time'] = nfl_small2['Start_Time'] + nfl_small2['diff']

In [98]:
# Exploring overtime diff, finding overtime records
nfl_small2[nfl_small2['qtr']==5].head(3)

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass,Start_Time,diff,Estimated_Time
3188,366120,4307,2017091702,2017-09-17,10:00,600.0,600.0,600.0,Overtime,0,5,IND,ARI,IND,home,ARI,ARI,35.0,23,0,NaN,0.0,ARI 35,0,0,P.Dawson kicks 69 yards from ARI 35 to IND -4....,kickoff,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,02:59:51,2017-09-17 15:59:51
3189,366121,4331,2017091702,2017-09-17,09:55,595.0,595.0,595.0,Overtime,0,5,IND,ARI,IND,home,ARI,IND,74.0,23,0,1.0,0.0,IND 26,10,0,(9:55) (Run formation) J.Brissett pass short m...,pass,0.0,short,10.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,03:00:06,2017-09-17 16:00:06
3190,366122,4357,2017091702,2017-09-17,09:47,587.0,587.0,587.0,Overtime,0,5,IND,ARI,ARI,away,IND,IND,21.0,24,0,1.0,0.0,IND 21,10,1,(9:47) (Run formation) W.Holden reported in as...,run,1.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,03:00:30,2017-09-17 16:00:30

In [99]:
# Exploring overtime diff, exploring one game
nfl_small2[(nfl_small2['game_id']==2017091702) & (nfl_small2['play_id'].between(4100,4400))].head(5)

,index,play_id,game_id,game_date,time,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,qtr,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,drive,sp,down,goal_to_go,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,pass_length,air_yards,yards_after_catch,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,td_team,total_home_score,total_away_score,posteam_score,defteam_score,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,fumble,complete_pass,Start_Time,diff,Estimated_Time
3181,366113,4128,2017091702,2017-09-17,00:17,17.0,17.0,17.0,Half2,0,4,IND,ARI,ARI,away,IND,IND,31.0,22,0,1.0,0.0,IND 31,10,23,(:17) (Run formation) C.Palmer left guard to I...,run,3.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,02:59:09,2017-09-17 15:59:09
3182,366114,4149,2017091702,2017-09-17,00:12,12.0,12.0,12.0,Half2,0,4,IND,ARI,ARI,away,IND,IND,31.0,22,0,NaN,0.0,IND 31,0,23,Timeout #2 by IND at 00:12.,no_play,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,02:59:24,2017-09-17 15:59:24
3183,366115,4166,2017091702,2017-09-17,00:12,12.0,12.0,12.0,Half2,0,4,IND,ARI,ARI,away,IND,IND,28.0,22,0,2.0,0.0,IND 28,7,27,(:12) (Run formation) C.Palmer kneels to IND 2...,no_play,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,02:59:24,2017-09-17 15:59:24
3184,366116,4209,2017091702,2017-09-17,00:09,9.0,9.0,9.0,Half2,0,4,IND,ARI,ARI,away,IND,IND,23.0,22,0,2.0,0.0,IND 23,2,27,(:09) C.Palmer kneels to IND 24 for -1 yards.,qb_kneel,-1.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,02:59:33,2017-09-17 15:59:33
3185,366117,4230,2017091702,2017-09-17,00:03,3.0,3.0,3.0,Half2,0,4,IND,ARI,ARI,away,IND,IND,23.0,22,0,NaN,0.0,IND 23,0,27,Timeout #3 by ARI at 00:03.,no_play,0.0,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,13,13,13.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2017-09-17 13:00:00,02:59:51,2017-09-17 15:59:51

In [101]:
# Saving nfl_small to csv to skip loading full file
nfl_small2.to_csv('nfl_small_cleaned.csv')